#!/bin/tcsh
#PBS -q workq
#PBS -A loni_nnlm6
#PBS -M shchen@phys.lsu.edu
#PBS -m ae
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:55:00
#PBS -j oe
#PBS -N AIS1

set WORK_DIR = /home/shaohao/program-basis/ais
set EXEC = ais-tdse

set NPROCS = `wc -l $PBS_NODEFILE |gawk '//{print $1}'`

cd $WORK_DIR

mpirun -machinefile $PBS_NODEFILE -np $NPROCS  $EXEC -on_error_attach_debugger

